theme: jekyll-theme-cayman
title: The Shape of Space
show_downloads: true
google_analytics: UA-125273633-1
repository: pharaohcola13/GeoExpanse

readme_index:
  enabled:          true
  remove_originals: false
